# Generated by Django 4.1.6 on 2023-02-21 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teambuilder", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="created_at",
            new_name="createdAt",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="updated_at",
            new_name="updatedAt",
        ),
    ]
