# Generated by Django 4.1.6 on 2023-02-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teambuilder", "0002_rename_created_at_team_createdat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
