# Generated by Django 4.1.6 on 2023-02-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teambuilder", "0004_team_players"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
