# Generated by Django 4.1.6 on 2023-02-22 06:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("teambuilder", "0005_alter_team_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
