# Generated by Django 4.1.6 on 2023-02-22 06:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("teambuilder", "0006_team_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
